var reasons = [
    "You're GORGEOUS!! SO SO SO PRETTY AHHH i still look at pics of u and wonder how u exist",
    "Your adorable smile :)",
    "Your cute little laugh hehe :3",
    "Your sweet voice! I listen to your VMs before bed sometimes because they help me sleep :)",
    "The way your voice gets soft when youre sleepy",
    "The softness in your pretty blue eyes :)",
    "ik its cliche but youre so pretty with or without makeup ur just like UGH youre AHHH youre a moving painting i swear",
    "Your hairrrrrrr jahqjaisksmsbs in any color and any style, somehow you just make everything look amazing",
    "When we kiss >3< mwah!",
    "All your adorable outfits!!",
    "All of your tattoos!! Yes even the puh bow!",
    "You're so kind even on days when you are grumpy",
    "The gifts you get people are so sweet. Like it's not just a happy birthday message, its stuff they would love and a cute card too! And then you say 'oh its not a lot' FUCK YOU!!",
    "Your drawings :) not just the drawings of me, all of them!",
    "Playing games together!!",
    "Making time for me and your friends even on busy days or when you are tired!",
    "Getting out of bed even on days when you really dont want to",
    "When you check on boyfie!",
    "When you send a VM or call and yap about literally anything",
    "All the things you collect like your albums and posters and dolls!",
    "How open you are with me + how much you trust me",
    "How honest / truthful you are",
    "The way you decorate your room / bed + all the cute plushies on the bed",
    "When you say my jokes (like rahhh or linter binkies or all the NATIONSSSS)",
    "Whenever you say 'i love you' (OBVIOUSLY HEHE)",
    "Whenever you send a post and say 'us'",
    "When you yap about any interest like Skz or shadowhunters :p",
    "This is a weird one: when you let me comfort you. Idk how to explain it but when smth is wrong and we talk or just sit together, its kinda cozy? idk. ",
    "Your favorite flower is the sunflower",
    "Everytime you send a picture of the sunset",
    "How much you hate Biondo (HE GOES IN SUN RAHHHH)",
    "Whenever we do your little hair routine hehe (PURPLE SPRAY WHOOOSSSS)",
    "When we play roblox and you say 'wheres my boyfriend?' >///<",
    "When you make me soups in 99 nights :p",
    "You build and decorate the whole base in 99 nights!",
    "When you say 'ooo shopping!' in 99 nights",
    "Whenever you do a phone makeover (the outside and the screens) and then show me :3",
    "When you call just to show me your stuff like from your trips or whats in your bag!!",
    "When you wake up from a nap and send that sleepy boykisser gif",
    "When you say mlem :p",
    "You teach me things about your physicsl / mental health! Like periods or bpd or bipolar or ARFID (and me tries to remember and learn as much as I can about them)",
    "You teach me polish words!! (And your favorite is szyszka!!)",
    "Your pouting / hmpfs / grrs when we do cute arguments :3",
    "You work so hard and do your best all the time!!",
    "You deal with shitty people all day but youre still so nice somehow?? Angel mentality fr",
    "Why is your heart still in your body? It should be in a museum!! It's so sweet and bright and shiny and pretty!!",
    "Even if you are far away I can feel your warmth!! You're always right next to me!!",
    "Youre gay. That's it, thats the whole sentence >:3",
    "Your fav colors are pink and black. Iconic",
    "The texts you send me while I'm sleeping!",
    "When you say you missed me!!",
    "When you say 'woof!' (yes puppy im watching 😉)",
    "You can do polish sign language?? LIKE WHAT AHH THATS AWESOME",
    "You're learning Italian!! Ti amo amore!!",
    "Talking with you is like a nice warm blanket. Always so safe and cozy!",
    "The way you switch between a whole black or whole pink theme. Phone, clothes, like thats so cute and its so you!!",
    "Whenever you do or say something silly and go 'mwehehe >:3'",
    "you like watermelon :>",
    "you have sooo many plushies hehe and give them cute names like sir william fishy sharky 🤭",
    "when you give me history lessons about poland",
    "when you tell me about cool stuff in your city :p",
    "you added a weather section / clock just for my city 🥹",
    "you HATE men!! rahhhh!!",
    "even your pepper spray is pimk like wtf, she a cutie even when she bullying men",
    "you bring your babcia flowers everytime you see her",
    "we hold hands when you pee :p",
    "WOOD NATIONNN YAYAYAYA",
    "you gives me cookies :3 woof!",
    "our little hide and seek whenever its eepy time for u hehe",
    "Your weird little dreams like being a possum and stealing planet earth in your backpack and getting caught at the airport",
    "how much you love italy! esp the smaller town like alberobello(idk if i spelled that right?) and the food!! maritozzo! and the lil fishies that eat your toes! and gab!!",
    "When you get cozy and watch your little comfort videos :3",
    "our cuddles!! yayay!!!",
    "you get eepy at 120 km/h hehehe",
    "'heart to heart, puh to puh'",
    "When you told me that you wished on birthdays for someone like me :((((",
    "When you told me i would be in your last 7 minutes :(((((",
    "When you repost tiktoks about me hehe",
    "Those times you call just to say i love you and then hang up xD",
    "You always ask if I am comfy with something before you do it! Like before we call or before you post about me!",
    "You keep me sane! You don't drain my battery! These days I don't talk to anyone other than you cuzzzz ur amazing and everyone else is bleh!",
    "You are incredibly mature and smart!! Even when youre splitting somehow!! Youre just a superhero I guess!!!",
    "You're so patient!! Even with assholes!! Or web after he ghosts for the 15th bajillionth time!! /j",
    "You're literally a gemius. You're so smart!! (even if you have a thing for dumbification /j, i will still always believe youre really smart!!)",
    "You might not believe this one but I think you face your fears very well. Fears are scary, obviously!! But you always seem to have some mechanism or just face them even if you are nervous or something like that!",
    "Even after talking everyday for like 6 months I still never get bored of talking to you. We always have something to talk about!",
    "Adorable little nose 🥹 mwah i kiss nose :3",
    "Just as you trust me, I trust you. And that is not a light thing! I dont trust anyone! At all! For example! You're the only person I *enjoy* calling and I didnt even call anyone since my high school crush like 4 years ago but even my calls with her were so boring! But not with you hehe",
    "Whenever you say 'im on my wayyyy' or do the thing where you kiss my tummy and heart and stuffs!",
    "Our little convos when you wake in the night :p",
    "You make time for me even when youre at work :O i so lucky!",
    "Youre so bright AHHH (insert spongebob meme: MY EYESSSSS) if i was a sunflower i would face you",
    "You bring a cute little bear in your bag ahhh",
    "You remember things like my fav color and kirby!! or stupid things like beavertails xD",
    "When you call me boyfie or husband OwO",
    "Whenever you send me a gif of kicking feet hehe",
    "Me when you send me a pic of yourself: me: *ded* random person: omg sir are you okay?? me: *revives* IM NOT A SIR *ded again* doctor: i see the problem. they saw a picture of their partner and she is, according to my important math and science notes, very fucking hot",
    "when you say you will play with my hair or put flowers in my hair or want me to play with your hair!!",
    "youre so squishy hehehe squishy girlfie *BIGGG SQUEEZEEEEEE*",
    "this is the 100th and last one i am writing, so nothing special here, I just wanted to say I love you so much sweetheart :) mwah!!"
]